## Logistic Regression Implementation

we'll also implement new ways to make a dataset

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [8]:
from sklearn.datasets import make_classification

## it'll help to create a dataset in a standardized way

In [9]:
X,Y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)  ## classes are output features

In [10]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]], shape=(1000, 10))

In [ ]:
# pd.DataFrame(X)

            0         1         2  ...         7         8         9
0    0.964799 -0.066449  0.986768  ... -1.210161 -0.628077  1.227274
1   -0.916511 -0.566395 -1.008614  ... -0.984534  0.363896  0.209470
2   -0.109484 -0.432774 -0.457649  ... -0.246383 -1.058145 -0.297376
3    1.750412  2.023606  1.688159  ... -0.357445 -1.473127 -0.190039
4   -0.224726 -0.711303 -0.220778  ... -0.939156  0.175915  0.236224
..        ...       ...       ...  ...       ...       ...       ...
995 -1.367638  1.462255 -1.154918  ...  1.428760  1.687092  1.072542
996 -1.514876 -3.221016 -1.300744  ... -1.680870  1.798510  0.034272
997  1.674633  1.754933  1.586154  ...  0.692723 -1.503850  0.225264
998 -0.778609 -0.835689 -0.194842  ... -0.497354  2.472138  0.867187
999  0.248454 -1.003439  0.360460  ...  0.773240  0.185734  1.416412

[1000 rows x 10 columns]